"""
Authentication helper for dkwholesale-com
Auto-generated by supplier_onboarding_wizard.py

⚠️ THIS IS A TEMPLATE - REQUIRES MANUAL CUSTOMIZATION
Edit this file to implement actual login flow for Dkwholesale
"""
import logging
from playwright.async_api import Page

log = logging.getLogger(__name__)

class DkwholesaleAuthenticationHelper:
    """Authentication helper for Dkwholesale."""

    def __init__(self, page: Page):
        self.page = page
        self.supplier_url = "https://dkwholesale.com"

    async def is_authenticated(self) -> bool:
        """
        Check if user is authenticated with price verification.

        WARNING: This includes MANDATORY price verification to confirm active session.
        Many sites show auth indicators even with expired sessions.
        """
        try:
            await self.page.goto(self.supplier_url, wait_until="domcontentloaded", timeout=10000)

            # Dkwholesale authentication indicators (Shopify-specific)
            account_indicators = [
                'a[href*="/account"]',
                'summary[aria-label*="Account"]',
                'a[href*="/logout"]',
                '.customer-logout',
                'header-login [data-icon-account]'
            ]

            for selector in account_indicators:
                element = await self.page.query_selector(selector)
                if element:
                    log.info(f"✅ Auth indicator found: {selector}")

                    # MANDATORY: Verify price access to confirm active session
                    # Without this, you may get false positives from stale cookies
                    price_verified = await self.verify_price_access()
                    if price_verified:
                        log.info("✅ Authentication confirmed with price access")
                        return True
                    else:
                        log.warning("⚠️ Auth indicator found but price verification failed - session may be stale")
                        return False

            # Alternative check: no login form present
            login_form = await self.page.query_selector('form[action*="/login"]')
            if not login_form:
                log.info("✅ No login form present - assuming authenticated")
                # Still verify price access to be certain
                price_verified = await self.verify_price_access()
                if price_verified:
                    return True
                else:
                    log.warning("⚠️ No login form but price verification failed")

            log.info("❌ User is not authenticated")
            return False

        except Exception as e:
            log.warning(f"Authentication check failed: {e}")
            # Fail-safe: assume not authenticated on error
            return False

    async def login(self, credentials: dict) -> bool:
        """
        Perform login using provided credentials.

        Args:
            credentials: Dict with 'username' and 'password' keys

        Returns:
            True if login successful, False otherwise

        TODO: Customize this method based on Dkwholesale's login flow.
        Steps typically include:
        1. Navigate to login page
        2. Fill username field
        3. Fill password field
        4. Click submit button
        5. Wait for authentication confirmation
        """
        try:
            username = credentials.get('username')
            password = credentials.get('password')

            if not username or not password:
                log.error("Missing username or password in credentials")
                return False

            login_url = "https://dkwholesale.com/account/login"
            log.info(f"Navigating to {login_url} for login...")
            await self.page.goto(login_url, wait_until="domcontentloaded")

            # Dkwholesale-specific login flow
            # Based on site analysis: uses Shopify-style login form
            log.info("Filling login form...")

            # Fill email field
            # CRITICAL: Use #CustomerEmail (visible) not #RecoverEmail (invisible)
            # Based on Chrome DevTools analysis, #RecoverEmail has 0x0 dimensions
            log.info(f"  → Entering email: {username}")
            await self.page.fill('#CustomerEmail', username)

            # Fill password field
            log.info("  → Entering password")
            await self.page.fill('#CustomerPassword', password)

            # Click login button
            # CRITICAL: Use text-based selector to find the "Sign in" button specifically
            # button[type="submit"] is too generic and may click wrong buttons
            log.info("  → Clicking login button")
            await self.page.click('button:text("Sign in")')

            # Wait for navigation/confirmation
            log.info("  → Waiting for authentication...")
            try:
                # Wait for either navigation or the account page to load
                await self.page.wait_for_load_state('networkidle', timeout=5000)
            except Exception:
                # Fallback to timeout if networkidle doesn't trigger
                await self.page.wait_for_timeout(3000)

            # Verify authentication success
            is_auth = await self.is_authenticated()
            if is_auth:
                log.info("✅ Login successful")
                return True

            log.error("❌ Login failed - authentication check returned False")
            # Take screenshot for debugging
            screenshot_path = "OUTPUTS/dkwholesale_login_failed.png"
            await self.page.screenshot(path=screenshot_path)
            log.error(f"📸 Screenshot saved to: {screenshot_path}")
            return False

        except Exception as e:
            log.error(f"Login failed with exception: {e}")
            # Take screenshot on error
            try:
                screenshot_path = "OUTPUTS/dkwholesale_login_error.png"
                await self.page.screenshot(path=screenshot_path)
                log.error(f"📸 Error screenshot saved to: {screenshot_path}")
            except:
                pass
            return False

    async def verify_price_access(self, page: Page = None) -> bool:
        """
        Verify that logged-in user can see wholesale prices with currency symbols.

        This method is CRITICAL for confirming active authentication.
        Many sites show "My Account" links even when sessions expire.
        Price verification is the ONLY reliable confirmation.

        Args:
            page: Optional page object to use (uses self.page if not provided)

        Returns:
            bool: True if price access is verified, False otherwise

        Reference: See sample_data/reference_auth/poundwholesale/supplier_authentication_service.py
        """
        try:
            log.info("🔍 Verifying price access...")

            # Use provided page or default to self.page
            target_page = page or self.page

            if not target_page:
                log.error("No page available for price verification")
                return False

            # Get test product URL from workflow config
            test_product_url = "https://dkwholesale.com/products/lorus-ladies-automatic-fashion-day-date-analogue-quartz-silver-sunray-dial-with-blue-leather-strap-watch"

            try:
                await target_page.goto(test_product_url, wait_until='domcontentloaded')
                await target_page.wait_for_timeout(3000)
            except Exception as e:
                log.error(f"Navigation error during price verification: {e}")
                return False

            # Look for price elements with currency symbols
            # IMPORTANT: Shopify sites often use different selectors
            price_selectors = [
                'span.price',                    # Standard price selector
                '.price',                        # Generic price class
                '[data-price]',                  # Data attribute
                'meta[property="product:price:amount"]',  # Meta tag
                '.product-price',                # Product price
                '.money',                        # Shopify money format
                '.woocommerce-Price-amount'      # WooCommerce fallback
            ]

            for selector in price_selectors:
                try:
                    elements = await target_page.locator(selector).all()
                    for element in elements:
                        if await element.is_visible():
                            text = await element.text_content()
                            if text and '£' in text and len(text.strip()) > 1:
                                # Validate it's a real price, not just text containing £
                                import re
                                price_pattern = r'£\s*\d+\.?\d*'
                                if re.search(price_pattern, text):
                                    log.info(f"✅ Price access confirmed: {text.strip()}")
                                    return True
                except Exception:
                    continue

            # Look for "login required" messages
            login_required_indicators = [
                'text=Login to view prices',
                'text=Sign in to see prices',
                'text=Login required'
            ]

            for indicator in login_required_indicators:
                try:
                    element = await target_page.locator(indicator).first
                    if await element.is_visible():
                        log.warning(f"⚠️ Found login required message: {indicator}")
                        return False
                except Exception:
                    continue

            log.warning("⚠️ Could not verify price access - no price found")
            # Take screenshot for debugging
            await target_page.screenshot(
                path="OUTPUTS/dkwholesale_price_verification_failed.png"
            )
            return False

        except Exception as e:
            log.error(f"Error verifying price access: {e}")
            return False
