{
  "asin_from_details": "B00XJKGQKG",
  "title": "BRUT Attraction Totale Aftershave",
  "current_price": 6.12,
  "main_image": "https://m.media-amazon.com/images/I/51yga2gHJqL._AC_SL1500_.jpg",
  "thumbnails": [
    "https://m.media-amazon.com/images/I/31Cr9bMnMsL._SL1500_.jpg",
    "https://m.media-amazon.com/images/I/31Bivog6gHL._SL1500_.jpg",
    "https://m.media-amazon.com/images/I/31N-3iY6WaL._SL1500_.jpg",
    "https://m.media-amazon.com/images/I/51nh3J0SwOL._SL1500_.jpg",
    "https://m.media-amazon.com/images/I/41bO3xUyykL._SL1500_.jpg",
    "https://m.media-amazon.com/images/I/61gx3TT1jlL._SL1500_BG85,85,85_BR-120_PKdp-play-icon-overlay__.jpg"
  ],
  "high_res_gallery": [],
  "amazon_product_details_section": {
    "Date First Available": "1 Dec. 2015",
    "Is discontinued by manufacturer\n                                    ‚Äè\n                                    :\n                                    ‚Äé": "No",
    "Product Dimensions\n                                    ‚Äè\n                                    :\n                                    ‚Äé": "3.2 x 9.7 x 12.3 cm; 260 g",
    "Manufacturer\n                                    ‚Äè\n                                    :\n                                    ‚Äé": "CRMA4",
    "ASIN\n                                    ‚Äè\n                                    :\n                                    ‚Äé": "B00XJKGQKG",
    "Item model number\n                                    ‚Äè\n                                    :\n                                    ‚Äé": "835-9416",
    "Delivery information": ": We cannot deliver certain products outside mainland UK ( Details). We will only be able to confirm if this product can be delivered to your chosen address when you enter your delivery address at checkout.",
    "Customer reviews": "4.3 4.3 out of 5 stars (523) var dpAcrHasRegisteredArcLinkClickAction; P.when('A', 'ready').execute(function(A) { if (dpAcrHasRegisteredArcLinkClickAction !== true) { dpAcrHasRegisteredArcLinkClickAction = true; A.declarative( 'acrLink-click-metrics', 'click', { \"allowLinkDefault\": true }, function (event) { if (window.ue) { ue.count(\"acrLinkClickCount\", (ue.count(\"acrLinkClickCount\") || 0) + 1); } } ); } }); P.when('A', 'cf').execute(function(A) { A.declarative('acrStarsLink-click-metrics', 'click', { \"allowLinkDefault\" : true }, function(event){ if(window.ue) { ue.count(\"acrStarsLinkWithPopoverClickCount\", (ue.count(\"acrStarsLinkWithPopoverClickCount\") || 0) + 1); } }); });",
    "Is discontinued by manufacturer\n                                    ‚Äè": "‚Äé No",
    "Product Dimensions\n                                    ‚Äè": "‚Äé 3.2 x 9.7 x 12.3 cm; 260 g",
    "Manufacturer\n                                    ‚Äè": "‚Äé CRMA4",
    "ASIN\n                                    ‚Äè": "‚Äé B00XJKGQKG",
    "Item model number\n                                    ‚Äè": "‚Äé 835-9416"
  },
  "date_first_available_from_details": "1 Dec. 2015",
  "manufacturer_from_details": "‚Äé CRMA4",
  "prime_eligible": true,
  "fulfilled_by_amazon": false,
  "seller_info_text": "Deals For You UK",
  "sold_by_amazon": false,
  "rating": 4.3,
  "review_count": 523,
  "availability_text": "In stock",
  "in_stock": true,
  "features": [
    "BRUT Attraction Totale Aftershave 100ml.",
    "SENSUAL fragrance of Paris",
    "A sensual woody fragrance enriched with a blend of citrus fruits notes and white musk.",
    "The electrifying charisma of a confident man",
    "100ml Bottle"
  ],
  "description": "Product Description The Essence of Man is what lies at the very core of every man. Brut brand value personifies the aspiration in the relentless pursuit of the identity of man, which is fueled by the essence. Brut products are customized for men who are passionate in sophistication, energetic in life, confident in attitude and modern in style. The Brut man exemplifies the identity, quality and individuality of a man, with a scent of European luxury. - Attraction Totale is the SENSUAL fragrance of Paris. The electrifying charisma of a confident man. Ingredients Alchohol Denat, Aqua,parfum,PEG-40 Hydrogenated Castor oil, Ethlhexyl Methoxycinnamate, Butyl Methoxydibenzoylmethane, Ethylhexyl Salicylate, Alpha-Isomethyl Ionone, Benzyl Alchohol, Benzyl Benzoate, Benzyl Salicylate, Butylpheny Methlpropional, Citral, Citronellol, Coumarin, Eugenol, Evernia Furfuracea, Geraniol, Hexyl Cinnamal, Hydroxycitronellal, Hydroxyisohexyl 3 ‚Äì Cyclohexene Carboxaldehyde, Isoeugenol, limonene, linalool. Safety Warning FOR EXTERNAL USE ONLY Box Contains 1 X 100ml Bottle See more",
  "specifications_table": {
    "Manufacturer": "‚ÄéCRMA4",
    "Package dimensions": "‚Äé12.2 x 8.4 x 2.4 centimetres",
    "Package Weight": "‚Äé0.26 Kilograms",
    "Item dimensions L x W x H": "‚Äé32 x 97 x 123 millimetres",
    "Item weight": "‚Äé260 Grams",
    "Brand": "‚ÄéBRUT",
    "Colour": "‚ÄéWhite",
    "Volume": "‚Äé100 Millilitres",
    "Scent": "‚Äécitrus",
    "Special features": "‚ÄéSensitive Skin",
    "Target audience": "‚ÄéMen",
    "Item model number": "‚Äé835-9416",
    "Product Dimensions": "‚Äé3.2 x 9.7 x 12.3 cm; 260 g",
    "ASIN": "‚ÄéB00XJKGQKG"
  },
  "selleramp": {
    "status": "SellerAmp extraction disabled"
  },
  "keepa": {
    "status": "Extraction process completed",
    "sales_rank_details_table": {
      "main_cat_current_rank": 13994,
      "main_cat_name": "Health & Personal Care 16 drops / month",
      "sub_cat_current_rank": 29,
      "sub_cat_name": "Aftershave Lotions & Fluids 4"
    },
    "ai_graph_analysis_status": "Keepa Graph AI Analysis disabled",
    "product_details_tab_data": {
      "Title": "BRUT Attraction Totale Aftershave",
      "Sales Rank - Reference": "Health & Personal Care",
      "Sales Rank - Display Group": "health_and_beauty_display_on_website",
      "Bought in past month": "100+",
      "Reviews - Rating": 4.3,
      "Reviews - Rating Count": 523.0,
      "Last Price Change": "1 minute ago",
      "Buy Box Seller": "Deals For You UK (99% positive over last 12 months)",
      "Lowest FBA Seller": "Deals For You UK (99% positive over last 12 months) IZORA (75% positive over last 12 months) TopKnotch Product (100% positive over last 12 months) Good Stuff Distribution (100% positive over last 12 months)",
      "FBA Pick&Pack Fee": 1.97,
      "Referral Fee %": "8.01 %",
      "Referral Fee based on current Buy Box price": 0.49,
      "Lowest FBM Seller": "Essentialsinstock (89% positive over last 12 months)",
      "Total Offer Count": "7",
      "Tracking since": "2016/12/13",
      "Listed since": "2015/12/01",
      "Categories - Root": "Health & Personal Care",
      "Categories - Sub": "Lotions & Fluids",
      "Categories - Tree": "Health & Personal Care ‚Ä∫ Shaving & Hair Removal ‚Ä∫ Post-Treatments ‚Ä∫ Aftershaves ‚Ä∫ Lotions & Fluids",
      "Website Display Group - Name": "Beauty",
      "ASIN": "B00XJKGQKG",
      "Product Codes - EAN": "8712561803847",
      "Product Codes - PartNumber": "835-9416",
      "Freq. Bought Together": "B01KXQ5TCY",
      "Type": "BEAUTY",
      "Manufacturer": "CRMA4",
      "Brand": "BRUT",
      "Product Group": "Beauty",
      "Model": "835-9416",
      "Color": "White",
      "Size": "100 ml (Pack of 1)",
      "Unit Details - Unit Value": "100",
      "Unit Details - Unit Type": "millilitre",
      "Scent": "citrus",
      "Style": "Modern",
      "Target Audience": "Unisex Adult",
      "Binding": "Personal Care",
      "Number of Items": "1",
      "Release Date": "2022-01-01",
      "Languages": "English: Manual",
      "Videos - Video Count": "1",
      "Videos - Main Videos": "Creator: Main, https://m.media-amazon.com/images/I/61gx3TT1jlL.jpg, https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-eu-west-1-prod/3efbe385-8e1f-4671-a8cc-9534d752831a/default.jobtemplate.hls.m3u8",
      "Package - Dimension (cm¬≥)": "12.2 x 8.4 x 2.4 cm (= 246 cm¬≥ )",
      "Package - Weight (g)": "260",
      "Package - Quantity": "1",
      "Item - Dimension (cm¬≥)": "3.2 x 9.7 x 12.3 cm (= 382 cm¬≥ )",
      "Item - Model (g)": "260",
      "Ingredients": "Alchohol Denat, Aqua,parfum,PEG-40 Hydrogenated Castor oil, Ethlhexyl Methoxycinnamate, Butyl Methoxydibenzoylmethane, Ethylhexyl Salicylate, Alpha-Isomethyl Ionone, Benzyl Alchohol, Benzyl Benzoate, Benzyl Salicylate, Butylpheny Methlpropional, Citral, Citronellol, Coumarin, Eugenol, Evernia Furfuracea, Geraniol, Hexyl Cinnamal, Hydroxycitronellal, Hydroxyisohexyl 3 ‚Äì Cyclohexene Carboxaldehyde, Isoeugenol, limonene, linalool.",
      "Safety Warning": "FOR EXTERNAL USE ONLY",
      "Hazardous Materials": "Proper Shipping Name: United Nations Regulatory Id: Regulatory Packing Group: PERFUMERY PRODUCTSUN1266II(more values available, copy cell to get all)"
    }
  },
  "eans_on_page": [
    "8712561803847"
  ],
  "ean_on_page_source": "Keepa_Product_Details",
  "ean_on_page": "8712561803847",
  "sales_rank": 13994,
  "category": "Health & Personal Care 16",
  "sales_rank_source": "Keepa_SalesRankDetailsTable",
  "estimated_monthly_sales_from_bsr": 20,
  "asin_extracted_from_page": "B00XJKGQKG",
  "asin_queried": "B00XJKGQKG",
  "asin": "B00XJKGQKG",
  "_search_method_used": "EAN_cached"
}                                                                                                                                                                                                                                                                                                                  ackup.format_fixes_backup_20250717_181444.test_financial_report.output_dirP£ÍÅÇbackup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractor._extract_product_details_amazonP†ørÅcbackup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractor._extract_priceP†∏wÅmbackup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractor._extract_keepa_dataP†≤sÅebackup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractor._extract_imagesP†≈uÅibackup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractor._extract_all_dataP† |Åwbackup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractor._estimate_sales_from_bsrP†ΩÅ}backup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractor._calculate_title_similarityP†µÅ Åbackup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractor._ai_extract_field_from_imageP†¥Å}backup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractor._ai_extract_field_from_htmlP†≥ÅÇbackup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractor._ai_diagnose_navigation_failureP†±ÅÇbackup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractor._ai_diagnose_extraction_failureP†¬lÅWbackup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractor.__init__P†ØcÅEbackup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractor.AmazonExtractorP†ªSÅ%backup.format_fixes_backup_20250717_181444.tools.amazon_playwright_extractorP†∆TÅ'backup.format_fixes_backup_20250717_181444.tools.FBA_Financial_calculator.logPéF]Å9backup.format_fixes_backup_20250717_181444.tools.FBA_Financial_calculator._linking_mapPéIXÅ/backup.format_fixes_backup_20250717_181444.tools.FBA_Financial_calculator._configPéBYÅ1backup.format_fixes_backup_20250717_181444.tools.FBA_Financial_calculator.VAT_RATEPéClÅWbackup.format_fixes_backup_20250717_181444.tools.FBA_Financial_calculator.SUPPLIER_PRICES_INCLUDE_VATPéEZÅ3backup.format_fixes_backup_20250717_181444.tools.FBA_Financial_calculator.SHIP_COSTPéHZÅ3backup.format_fixes_backup_20250717_181444.tools.FBA_Financial_calculator.PREP_COSTPéD[Å5backup.format_fixes_backup_20250717_181444.tools.FBA_Financial_calculator.OUTPUT_DIRPéAYÅ1backup.format_fixes_backup_20250717_181444.tools.FBA_Financial_ca{
  "asin_from_details": "B00X41ZTAI",
  "title": "SELF ADHESIVE ALUMINIUM FOIL TAPE SILVER ELECTRIC HEAT REFLECTOR PIPE REPAIR 10m x 50mm",
  "current_price": 5.29,
  "original_price": 5.65,
  "main_image": "https://m.media-amazon.com/images/I/61ol0HcOYqL._SL1145_.jpg",
  "thumbnails": [
    "https://m.media-amazon.com/images/I/41