# -*- coding: utf-8 -*-
"""
Pre-Flight Calibration Configuration: part_1_jan.xlsx
======================================================
Generated: 2026-01-02 03:50 UTC+4
File Analyzed: part_1_jan.xlsx
Rows Analyzed: 50

This configuration was auto-generated by the Pre-Flight Calibration Analysis.
Paste this into your main analysis script or import directly.
"""

import re

# --- CALIBRATION CONFIGURATION: part_1_jan.xlsx ---

SUPPLIER_NAMING_CONVENTION = {
    # Pack quantity explicit unit markers
    "explicit_units": ["pc", "pcs", "pce", "pk", "pack", "pieces"],
    
    # Allow trailing numbers as pack qty with context validation
    "allow_trailing_number_as_qty": True,
    
    # No leading multiplier patterns found (e.g., "10x Product")
    "leading_multiplier_check": False,
    
    # Dimension/Measurement keywords - DO NOT interpret as pack quantities
    "dimension_shield_keywords": [
        "cm", "mm", "m",           # Length
        "ml", "l", "ltr",          # Volume  
        "g", "kg", "oz",           # Weight
        "w", "watt",               # Power
        "inch", "in"               # Imperial
    ],
    
    # Brand naming is inconsistent
    "brand_position": "mixed",
    
    # Sales data column (clean integers, no parsing needed)
    "sales_column": "bought_in_past_month",
    
    # Additional dimension patterns that contain 'x' (NOT multipliers)
    "dimension_x_patterns": [
        r"\d+[xX]\d+\s*cm",        # 70X100CM (bag dimensions)
        r"\d+\s*[xX]\s*\d+\s*mm",  # 5X60MM, 5MM X 85MM (screw/drill dimensions)
    ],
    
    # Model number patterns (trailing alphanumerics, NOT pack qty)
    "model_number_patterns": [
        r"[A-Z]{2,}\d{2,}$",       # SDB113
    ],
    
    # Variant/Style indicators (if these words precede a trailing number, it's NOT pack qty)
    "variant_indicators": [
        "girl", "boy", "age", "size", "style", "number", "decor", "no.", "#", "grade", "type"
    ]
}

# --- CALIBRATION WARNINGS: KNOWN TRAP ROWS ---
# These are specific rows from part_1_jan.xlsx that may trap generic logic

KNOWN_TRAP_ROWS = {
    0: {
        "title": "EUROWRAP GIANT BIRTHDAY BADGE GIRL 3",
        "trap": "Trailing '3' is age variant, NOT pack qty",
        "correct_pack": 1
    },
    16: {
        "title": "PANASONIC UPRIGHT SDB113",
        "trap": "Trailing '113' is model number, NOT pack qty",
        "correct_pack": 1
    },
    34: {
        "title": "UNIQUE CANDLE NUMBER W/DECOR 6",
        "trap": "Trailing '6' is birthday candle number, NOT pack qty",
        "correct_pack": 1
    },
    10: {
        "title": "EASY STORAGE VACUUM BAG 70X100CM",
        "trap": "'70X100' are bag dimensions (70cm x 100cm), NOT pack qty",
        "correct_pack": 1
    },
    36: {
        "title": "SECURPAK POZI COUNTERSUNK SCREWS ZP 5X60MM",
        "trap": "'5X60' are screw dimensions, NOT 5 packs",
        "correct_pack": 1
    },
    37: {
        "title": "DEKTON MASONRY DRILL BIT 5MM X 85MM",
        "trap": "'5MM X 85MM' are drill bit dimensions, NOT pack qty",
        "correct_pack": 1
    },
}


# --- HELPER FUNCTIONS ---

def is_dimension_number(title: str, number: str) -> bool:
    """
    Check if a number in the title is part of a dimension/measurement.
    Returns True if the number should NOT be treated as pack quantity.
    """
    title_lower = title.lower()
    
    # Check if number is followed by dimension unit
    for unit in SUPPLIER_NAMING_CONVENTION["dimension_shield_keywords"]:
        pattern = rf"\b{number}\s*{unit}\b"
        if re.search(pattern, title_lower, re.IGNORECASE):
            return True
    
    # Check dimension X patterns (e.g., 70X100CM)
    for pattern in SUPPLIER_NAMING_CONVENTION["dimension_x_patterns"]:
        if re.search(pattern, title, re.IGNORECASE):
            return True
    
    return False


def is_variant_number(title: str) -> bool:
    """
    Check if a trailing number is a variant/style indicator.
    Returns True if the trailing number should NOT be treated as pack quantity.
    """
    title_lower = title.lower()
    
    for indicator in SUPPLIER_NAMING_CONVENTION["variant_indicators"]:
        if indicator in title_lower:
            # Check if indicator is near the end of title
            if title_lower.rfind(indicator) > len(title_lower) // 2:
                return True
    
    return False


def is_model_number(title: str, trailing_number: str) -> bool:
    """
    Check if a trailing number is part of a model number.
    Returns True if the trailing number should NOT be treated as pack quantity.
    """
    for pattern in SUPPLIER_NAMING_CONVENTION["model_number_patterns"]:
        if re.search(pattern, title, re.IGNORECASE):
            return True
    
    return False


def extract_pack_quantity(supplier_title: str) -> int:
    """
    Extract pack quantity from supplier title using calibration rules.
    
    Priority:
    1. Explicit unit markers (N PC, N PK, N PIECES)
    2. Pack-related words (N CASES)
    3. Validated trailing numbers
    4. Default to 1
    
    Returns: Pack quantity as integer
    """
    title = supplier_title.upper()
    
    # Priority 1: Explicit unit markers
    explicit_pattern = r'(\d+)\s*(' + '|'.join(SUPPLIER_NAMING_CONVENTION["explicit_units"]) + r')\b'
    match = re.search(explicit_pattern, title, re.IGNORECASE)
    if match:
        return int(match.group(1))
    
    # Priority 2: Pack-related words
    case_pattern = r'(\d+)\s*CASES?\b'
    match = re.search(case_pattern, title, re.IGNORECASE)
    if match:
        return int(match.group(1))
    
    # Priority 3: Trailing number (with validation)
    if SUPPLIER_NAMING_CONVENTION["allow_trailing_number_as_qty"]:
        trailing_match = re.search(r'(\d+)\s*$', title)
        if trailing_match:
            number = trailing_match.group(1)
            
            # Apply dimension shield
            if is_dimension_number(supplier_title, number):
                return 1
            
            # Apply variant check
            if is_variant_number(supplier_title):
                return 1
            
            # Apply model number check
            if is_model_number(supplier_title, number):
                return 1
            
            # Accept as pack quantity
            return int(number)
    
    # Default
    return 1


# --- USAGE EXAMPLE ---
if __name__ == "__main__":
    test_titles = [
        "LUXURY CUPCAKE 100 CASES",              # Should be 100
        "FESTIVE MAGIC BELLS 8PC ASSORTED",      # Should be 8
        "DLUX PEGS WITH SOFT RUBBER GRIP PLASTIC LARGE 12 PIECES",  # Should be 12
        "EUROWRAP GIANT BIRTHDAY BADGE GIRL 3",  # Should be 1 (variant)
        "PANASONIC UPRIGHT SDB113",              # Should be 1 (model)
        "EASY STORAGE VACUUM BAG 70X100CM",      # Should be 1 (dimensions)
        "PARTY CRAZY BALLOONS ASSORTED 20",      # Should be 20
        "I LOVE YOU BALLOON 40CM",               # Should be 1 (dimension)
    ]
    
    print("Pack Quantity Extraction Test Results:")
    print("-" * 60)
    for title in test_titles:
        qty = extract_pack_quantity(title)
        print(f"{title}")
        print(f"  -> Pack Qty: {qty}")
        print()
